// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elalelsdbctkgylkzlyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsYWxlbHNkYmN0a2d5bGt6bHl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNjYzOTIsImV4cCI6MjA1MzY0MjM5Mn0.6Jo9gbH7TyFcsUKiZzl3iPx4g6-hfzFccgzSoKg14fo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);